export const CHAT_PARTICIPANT_ID = "vscode-grug";

export const BLOG_THOUGHT_SECTIONS = [
  "agile.md",
  "APIs.md",
  "chestertonsFence.md",
  "closures.md",
  "concurrency.md",
  "DRY.md",
  "eternalEnemyComplexity.md",
  "expressionComplexity.md",
  "factoringYourCode.md",
  "fads.md",
  "fearOfLookingDumb.md",
  "frontEndDevelopment.md",
  "imposterSyndrome.md",
  "introduction.md",
  "logging.md",
  "microservices.md",
  "optimizing.md",
  "parsing.md",
  "refactoring.md",
  "sayingNo.md",
  "sayingOk.md",
  "separationOfConcerns.md",
  "testing.md",
  "tools.md",
  "typeSystems.md",
  "visitorPattern.md",
];
